services:
  limits-service:
    image: docker.io/firstmicro/demo:v1
    mem_limit: 700m
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka"
      - "SPRING_PROFILES_ACTIVE=eureka"


  naming-server:
    image: docker.io/balanceload/balance:v1
    mem_limit: 700m
    ports:
      - "8761:8761"

  first_micro:
    image: docker.io/sendermicro/fmicro:v1
    mem_limit: 700m

    depends_on:
      - naming-server
    ports:
      - "8081:8081"
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka"
      - "SPRING_PROFILES_ACTIVE=eureka"


  api-gateway:
    image: docker.io/gateway/api-gateway:v1
    mem_limit: 700m
    depends_on:
      - naming-server
    ports:
      - "8765:8765"
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka"



